# Generated by Django 6.0.5 on 2026-06-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_rooms_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('guest_name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('room_snapshot_number', models.CharField(db_index=True, max_length=50)),
                ('room_snapshot_type', models.CharField(db_index=True, max_length=150)),
                ('check_in', models.DateTimeField(db_index=True)),
                ('check_out', models.DateTimeField(db_index=True)),
                ('booking_source', models.CharField(default='Walk-in', max_length=100)),
                ('purpose_of_visit', models.CharField(blank=True, default='', max_length=255)),
                ('adults_count', models.IntegerField(default=1)),
                ('children_count', models.IntegerField(default=0)),
                ('extra_bed', models.BooleanField(default=False)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('state', models.CharField(blank=True, default='', max_length=150)),
                ('country', models.CharField(default='India', max_length=150)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out'), ('Cancelled', 'Cancelled')], db_index=True, default='Confirmed', max_length=50)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_relation', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('luggage_count', models.IntegerField(default=0)),
                ('smoking_preference', models.CharField(default='Non-Smoking', max_length=50)),
                ('id_type', models.CharField(blank=True, default='', max_length=100)),
                ('id_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('passport_number', models.CharField(blank=True, default='', max_length=100)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_number', models.CharField(blank=True, default='', max_length=100)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('country_of_issue', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.rooms')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('id_type', models.CharField(blank=True, default='', max_length=100)),
                ('id_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('document_file', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary_guest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.booking')),
            ],
            options={
                'db_table': 'BookingGuest',
            },
        ),
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(db_index=True, max_length=100)),
                ('front_file', models.CharField(blank=True, default='', max_length=255)),
                ('back_file', models.CharField(blank=True, default='', max_length=255)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.booking')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.bookingguest')),
            ],
            options={
                'db_table': 'BookingDocument',
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], db_index=True, default='Pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking')], default='Cash', max_length=50)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='booking.booking')),
            ],
            options={
                'db_table': 'BookingPayment',
            },
        ),
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Advance', 'Advance'), ('Payment', 'Payment'), ('Refund', 'Refund')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking')], default='Cash', max_length=50)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='booking.booking')),
            ],
            options={
                'db_table': 'BookingTransaction',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_code', 'status'], name='Booking_booking_3c13c9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_name', 'phone'], name='Booking_guest_n_ccaa5b_idx'),
        ),
    ]
