# Generated by Django 6.0.5 on 2026-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guests',
            field=models.IntegerField(default=1),
        ),
    ]
