export const MOCK_ROOMS = [
  {
    id: '101',
    roomNumber: '101',
    type: 'Classic Queen',
    floor: '1st Floor',
    status: 'available',
    price: 3500,
    capacity: 2,
    bedType: 'Queen',
    amenities: ['WiFi', 'AC', 'TV', 'Room Service'],
    description: 'A cozy and charming room perfect for leisure and business travelers. Offers elegant modern styling, premium bedding, and a peaceful garden view.',
    images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '2 hrs ago'
  },
  {
    id: '102',
    roomNumber: '102',
    type: 'Classic Queen',
    floor: '1st Floor',
    status: 'occupied',
    price: 3500,
    capacity: 2,
    bedType: 'Queen',
    amenities: ['WiFi', 'AC', 'TV'],
    description: 'A stylish and comfortable lodging option equipped with ultra-fast WiFi, dual AC, smart TV, and plush premium Queen mattresses for deep sleep.',
    images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: 'Yesterday'
  },
  {
    id: '201',
    roomNumber: '201',
    type: 'Classic King',
    floor: '2nd Floor',
    status: 'dirty',
    price: 5500,
    capacity: 2,
    bedType: 'King',
    amenities: ['WiFi', 'AC', 'TV', 'Mini Bar'],
    description: 'An upgraded premium room option with an expansive California King size bed, premium acoustics, mini refreshment bar, and quiet central AC.',
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '5 hrs ago'
  },
  {
    id: '202',
    roomNumber: '202',
    type: 'Classic King',
    floor: '2nd Floor',
    status: 'available',
    price: 5500,
    capacity: 2,
    bedType: 'King',
    amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Safe'],
    description: 'A spacious and secure executive retreat. Includes in-room electronic safe, premium mini bar, fast WiFi, and floor-to-ceiling windows for natural light.',
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '1 hr ago'
  },
  {
    id: '301',
    roomNumber: '301',
    type: 'Deluxe Suite',
    floor: '3rd Floor',
    status: 'occupied',
    price: 9500,
    capacity: 3,
    bedType: 'Double Queen',
    amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Safe', 'Balcony', 'Room Service', 'Spa Lounge'],
    description: 'A lavish suite layout complete with double queen beds, a separate sitting lounge, private balcony overlooking the city skyline, and dedicated butler call service.',
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '3 hrs ago'
  },
  {
    id: '304',
    roomNumber: '304',
    type: 'Deluxe Suite',
    floor: '3rd Floor',
    status: 'maintenance',
    price: 9500,
    capacity: 3,
    bedType: 'Double Queen',
    amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Safe', 'Balcony', 'Room Service'],
    description: 'Luxurious double-queen suite currently undergoing planned standard maintenance checks for climate control and media connectivity setups.',
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '3 days ago'
  },
  {
    id: '401',
    roomNumber: '401',
    type: 'Executive Suite',
    floor: '4th Floor',
    status: 'available',
    price: 18000,
    capacity: 4,
    bedType: 'Double King',
    amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Safe', 'Balcony', 'Room Service', 'Jacuzzi', 'Valet Parking'],
    description: 'An elite suite for discerning travelers. Features double king beds, extensive living parlor, full-size luxury jacuzzi tub, and wrap-around private panoramic terrace.',
    images: ['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '30 mins ago'
  },
  {
    id: '501',
    roomNumber: '501',
    type: 'Presidential Penthouse',
    floor: '5th Floor',
    status: 'occupied',
    price: 45000,
    capacity: 6,
    bedType: 'Super King',
    amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Safe', 'Balcony', 'Room Service', 'Jacuzzi', 'Infinity Pool', 'Private Chef', 'Spa Lounge', 'Valet Parking'],
    description: 'The pinnacle of luxury living. Features multiple grand bedrooms, panoramic dining parlor, private rooftop infinity pool access, and full smart-home touch integrations.',
    images: ['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=500&auto=format&fit=crop&q=60'],
    lastCleaned: '4 hrs ago'
  }
];
