# Generated by Django 6.0.5 on 2026-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('floor', models.CharField(db_index=True, max_length=100)),
                ('room_type', models.CharField(db_index=True, max_length=150)),
                ('bed_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(db_index=True, default='available', max_length=100)),
                ('amenities', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('last_cleaned', models.CharField(blank=True, default='Just registered', max_length=100, null=True)),
                ('status_updated_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('status_updated_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
    ]
