# Generated by Django 6.0.5 on 2026-06-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rooms',
            table='Rooms',
        ),
    ]
