# Generated by Django 6.0.5 on 2026-06-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('uniqueCode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(db_index=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneCountry', models.CharField(max_length=10)),
                ('phoneNo', models.CharField(max_length=50)),
                ('emergencyCountry', models.CharField(max_length=10)),
                ('emergencyNo', models.CharField(max_length=50)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('isCheckedIn', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('govtProofType', models.CharField(max_length=100)),
                ('govtProofId', models.CharField(max_length=100)),
                ('govtProofFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('govtProofFileUrl', models.TextField(blank=True, null=True)),
                ('profileFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('profileFileUrl', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='shifts.shifts')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
