# Generated by Django 6.0.5 on 2026-06-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('unique_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(db_index=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_country', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=50)),
                ('emergency_country', models.CharField(max_length=10)),
                ('emergency_no', models.CharField(max_length=50)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('govt_proof_type', models.CharField(max_length=100)),
                ('govt_proof_id', models.CharField(max_length=100)),
                ('govt_proof_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('govt_proof_file_url', models.TextField(blank=True, null=True)),
                ('profile_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_file_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='shifts.shifts')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='staff.staff')),
            ],
            options={
                'db_table': 'StaffLog',
            },
        ),
    ]
