# Generated by Django 6.0.5 on 2026-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('time', models.CharField(max_length=100)),
                ('icon', models.CharField(default='clock', max_length=50)),
                ('color', models.CharField(default='purple', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Shifts',
            },
        ),
    ]
